### ISSUE TITLE
Connection to Uponor stops

### ISSUE THREAD

**Issue by TompaNation** [asev/homeassistant-uponor#29]
Hi

The integration works perfectly when I have setup it. But after a few days HA loses the connection and I need to restart / reconfigure the wifi ( or ethernet connection via RJ45, same issue with both). 
![Screenshot_20220212-090253_Home Assistant](https://user-images.githubusercontent.com/61341892/153703290-0105ab00-ca99-46ba-90e5-bde4b2e998e1.jpg)

The connection still works with the Uponor app. Have anyone else got this trouble? 
I know that some integrations/hardware needs to have a second user and password for it to work, else there is some kind of connection crash. 
How often is the integration pooling the Uponor? 

Except this problem I really like this integration! 

Best regards 
Tomas

**Comment by nisarerbest** [comment]
I have a very similar error. Posting the logs:


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/uponor/__init__.py:294
Integration: Uponor (documentation, issues)
First occurred: 02:38:39 (1 occurrences)
Last logged: 02:38:39

Error setting up entry Uponor for uponor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f98fe35cac0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.50.36', port=80): Max retries exceeded with url: /JNAP/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f98fe35cac0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/uponor/__init__.py", line 54, in async_setup_entry
    await state_proxy.async_update(0)
  File "/config/custom_components/uponor/__init__.py", line 294, in async_update
    self._data = await self._hass.async_add_executor_job(lambda: self._client.get_data())
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/uponor/__init__.py", line 294, in <lambda>
    self._data = await self._hass.async_add_executor_job(lambda: self._client.get_data())
  File "/usr/local/lib/python3.9/site-packages/UponorJnap/UponorJnap.py", line 9, in get_data
    r = requests.post(url=self.url, headers={"x-jnap-action": "http://phyn.com/jnap/uponorsky/GetAttributes"},
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.50.36', port=80): Max retries exceeded with url: /JNAP/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f98fe35cac0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by PMPoulsen** [comment]
I just experienced the same issue.

I made a restart after updateing a YAML config which were not related to Uponor. After the restart I was not able get it configured. Tried another restart, but still not able to configure.
Checked the IP address, no change still the same and I had also access from the APP

Then I removed the integration and reinstalled, then I was able to get it back up running.

So it appears as there is some kind of problem

**Comment by cstenager** [comment]
Same issue here, and have to remove and reinstall the integration

**Comment by vanjanis** [comment]
Hello! Same here. Already to times disconnected and only way to get back is to delete and setup again. Would be nice to be solved this.

**Comment by dave-code-ruiz** [comment]
Fork that solves most issues in this integration:

https://github.com/asev/homeassistant-uponor/issues/46
