### ISSUE TITLE
I cannot make it work - I get this error

### ISSUE THREAD

**Issue by poedk** [asev/homeassistant-uponor#8]
Logger: homeassistant.loader
Source: custom_components/uponor/__init__.py:14
First occurred: 23.40.28 (4 occurrences)
Last logged: 23.40.49

Error loading custom_components.uponor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 436, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/uponor/__init__.py", line 14, in <module>
    from UponorJnap import UponorJnap
ModuleNotFoundError: No module named 'UponorJnap'

**Comment by asev** [comment]
Hi.
Sorry for such a late response. I hope you've resolved this issue.
Please check if you have up to date `manifest.json` file in `/config/custom_components/uponor/` folder.
